### ISSUE TITLE
存在API无鉴权的漏洞

### ISSUE THREAD

**Issue by Zrincet** [devsapp/blindbox-game#1]
通过随机生成用户UID，通过接口获取实物中奖Token，通过接口填写收货地址信息实现批量中奖，并有可能清空奖池。

**Comment by anycodes** [comment]
感谢提醒。因为这个是直接复用之前的一个项目，在这次没有增加对uid的校验，算是工作失误，感谢指出，目前已经完成优化。

为了表示感谢，请加我好友，送你一份小礼物，钉钉：17302010206，或者微信：envless
